default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: ben
  password: <%= ENV['APPNAME_DATABASE_PASSWORD'] %>
  timeout: 5000

development:
  <<: *default
  database: subscriptions_development

test:
  <<: *default
  database: subscriptions_test
